[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:plantuml]
priority=10
command=java -jar /opt/jetty/start.jar jetty.home=/opt/jetty jetty.base=/opt/jetty-base
directory=/opt/jetty-base
environment=CONTEXT_PATH="/"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:backend]
priority=20
command=python gradio_app.py
directory=/app
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:frontend]
priority=30
command=node_modules/.bin/next start --hostname 0.0.0.0 --port 3000
directory=/app/app/frontend
environment=NEXT_PUBLIC_GRADIO_API_BASE="http://127.0.0.1:7860",NODE_ENV="production"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
