version: "3.8"

services:
  umlbot-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PROJECT_NAME: UMLBot
        PYTHON: "3.11"
        USERNAME: vscode
        NODE_VERSION: "none"
    volumes:
      - ..:/workspaces/UMLBot:cached
      - umlbot-venv:/workspaces/UMLBot/.venv
    command: sleep infinity

volumes:
  umlbot-venv:
