name: Trigger auto deployment for uml-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/uml-api-AutoDeployTrigger-ee65c9a1-e0ca-4210-8d57-69c8167b7dbe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UMLAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.UMLAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.UMLAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.UMLAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UMLAPI_REGISTRY_PASSWORD }}
          containerAppName: uml-api
          resourceGroup: anes-ai
          imageToBuild: ghcr.io/uml-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


